name: Docker Release Action
description: GitHub CI Action to deploy multi-platform docker images with configurable prefixes and reusable workflows.
branding:
  icon: 'package'
  color: 'blue'
inputs:
  registry:
    description: 'Container registry to push to (e.g., ghcr.io, docker.io)'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'Name of the Docker image (without prefix)'
    required: true
  image-prefix:
    description: 'Prefix to add to the image name (e.g., "my-org-")'
    required: false
    default: ''
  context:
    description: 'Build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  platforms:
    description: 'Target platforms for build'
    required: false
    default: 'linux/amd64,linux/arm64'
  push:
    description: 'Push the image to registry'
    required: false
    default: 'true'
  registry-username:
    description: 'Username for registry authentication'
    required: false
    default: '${{ github.actor }}'
  registry-password:
    description: 'Password for registry authentication'
    required: false
    default: '${{ github.token }}'

outputs:
  image:
    description: 'Full image name with tags'
    value: ${{ steps.meta.outputs.tags }}
  digest:
    description: 'Image digest'
    value: ${{ steps.push.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
        
    - name: Generate image name with prefix
      id: image-name
      run: |
        PREFIX="${{ inputs.image-prefix }}"
        IMAGE_NAME="${{ inputs.image-name }}"
        REGISTRY="${{ inputs.registry }}"
        
        if [ -n "$PREFIX" ]; then
          FULL_IMAGE_NAME="${PREFIX}${IMAGE_NAME}"
        else
          FULL_IMAGE_NAME="${IMAGE_NAME}"
        fi
        
        # Handle registry format - if it doesn't contain a slash, add the repository context
        if [[ "$REGISTRY" == "ghcr.io" ]]; then
          echo "full-name=${REGISTRY}/${{ github.repository_owner }}/${FULL_IMAGE_NAME}" >> $GITHUB_OUTPUT
        else
          echo "full-name=${REGISTRY}/${FULL_IMAGE_NAME}" >> $GITHUB_OUTPUT
        fi
      shell: bash
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ steps.image-name.outputs.full-name }}
        
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}